[package]
name = "quikcov-preload"
version = "0.1.0"
edition = "2021"
crate_type = ["dylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "*"
fxhash = "0.2"
